//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srCodigos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="srCodigos.ServicioFacturacionCodigos")]
    public interface ServicioFacturacionCodigos
    {
        
        // CODEGEN: El parámetro "RespuestaComunicacion" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaComunicacion")]
        srCodigos.verificarComunicacionResponse verificarComunicacion(srCodigos.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.verificarComunicacionResponse> verificarComunicacionAsync(srCodigos.verificarComunicacion request);
        
        // CODEGEN: El parámetro "RespuestaVerificarNit" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaVerificarNit")]
        srCodigos.verificarNitResponse verificarNit(srCodigos.verificarNit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.verificarNitResponse> verificarNitAsync(srCodigos.verificarNit request);
        
        // CODEGEN: El parámetro "RespuestaCuisMasivo" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCuisMasivo")]
        srCodigos.cuisMasivoResponse cuisMasivo(srCodigos.cuisMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.cuisMasivoResponse> cuisMasivoAsync(srCodigos.cuisMasivo request);
        
        // CODEGEN: El parámetro "RespuestaCufd" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCufd")]
        srCodigos.cufdResponse cufd(srCodigos.cufd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.cufdResponse> cufdAsync(srCodigos.cufd request);
        
        // CODEGEN: El parámetro "RespuestaNotificaRevocado" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaNotificaRevocado")]
        srCodigos.notificaCertificadoRevocadoResponse notificaCertificadoRevocado(srCodigos.notificaCertificadoRevocado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(srCodigos.notificaCertificadoRevocado request);
        
        // CODEGEN: El parámetro "RespuestaCuis" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCuis")]
        srCodigos.cuisResponse cuis(srCodigos.cuis request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.cuisResponse> cuisAsync(srCodigos.cuis request);
        
        // CODEGEN: El parámetro "RespuestaCufdMasivo" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaCufdMasivo")]
        srCodigos.cufdMasivoResponse cufdMasivo(srCodigos.cufdMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<srCodigos.cufdMasivoResponse> cufdMasivoAsync(srCodigos.cufdMasivo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCufdDto
    {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufdMasivo
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCufdDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCufdDto[] datosSolicitud
        {
            get
            {
                return this.datosSolicitudField;
            }
            set
            {
                this.datosSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuis
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudNotifcaRevocado
    {
        
        private string certificadoField;
        
        private int codigoAmbienteField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private System.Nullable<System.DateTime> fechaRevocacionField;
        
        private bool fechaRevocacionFieldSpecified;
        
        private long nitField;
        
        private string razonRevocacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> fechaRevocacion
        {
            get
            {
                return this.fechaRevocacionField;
            }
            set
            {
                this.fechaRevocacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRevocacionSpecified
        {
            get
            {
                return this.fechaRevocacionFieldSpecified;
            }
            set
            {
                this.fechaRevocacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string razonRevocacion
        {
            get
            {
                return this.razonRevocacionField;
            }
            set
            {
                this.razonRevocacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufd
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCuisDto
    {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuisMasivoSistemas
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCuisDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCuisDto[] datosSolicitud
        {
            get
            {
                return this.datosSolicitudField;
            }
            set
            {
                this.datosSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificarNit
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        private long nitParaVerificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nitParaVerificacion
        {
            get
            {
                return this.nitParaVerificacionField;
            }
            set
            {
                this.nitParaVerificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCufdSoapDto
    {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private string cuisField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl
        {
            get
            {
                return this.codigoControlField;
            }
            set
            {
                this.codigoControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public mensajeServicio[] mensajeServicioList
        {
            get
            {
                return this.mensajeServicioListField;
            }
            set
            {
                this.mensajeServicioListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCuisSoapDto
    {
        
        private string codigoField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajeServicioList
        {
            get
            {
                return this.mensajeServicioListField;
            }
            set
            {
                this.mensajeServicioListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufdMasivo : modelDto
    {
        
        private respuestaListaRegistroCufdSoapDto[] listaRespuestasCufdField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCufd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCufdSoapDto[] listaRespuestasCufd
        {
            get
            {
                return this.listaRespuestasCufdField;
            }
            set
            {
                this.listaRespuestasCufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuis : modelDto
    {
        
        private string codigoField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufd : modelDto
    {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl
        {
            get
            {
                return this.codigoControlField;
            }
            set
            {
                this.codigoControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuisMasivo : modelDto
    {
        
        private respuestaListaRegistroCuisSoapDto[] listaRespuestasCuisField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCuis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCuisSoapDto[] listaRespuestasCuis
        {
            get
            {
                return this.listaRespuestasCuisField;
            }
            set
            {
                this.listaRespuestasCuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConfiguracion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaNotificaRevocado : respuestaConfiguracion
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaVerificarNit : respuestaConfiguracion
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaComunicacion RespuestaComunicacion;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(srCodigos.respuestaComunicacion RespuestaComunicacion)
        {
            this.RespuestaComunicacion = RespuestaComunicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNit", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNit
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudVerificarNit SolicitudVerificarNit;
        
        public verificarNit()
        {
        }
        
        public verificarNit(srCodigos.solicitudVerificarNit SolicitudVerificarNit)
        {
            this.SolicitudVerificarNit = SolicitudVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNitResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaVerificarNit RespuestaVerificarNit;
        
        public verificarNitResponse()
        {
        }
        
        public verificarNitResponse(srCodigos.respuestaVerificarNit RespuestaVerificarNit)
        {
            this.RespuestaVerificarNit = RespuestaVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas;
        
        public cuisMasivo()
        {
        }
        
        public cuisMasivo(srCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas)
        {
            this.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaCuisMasivo RespuestaCuisMasivo;
        
        public cuisMasivoResponse()
        {
        }
        
        public cuisMasivoResponse(srCodigos.respuestaCuisMasivo RespuestaCuisMasivo)
        {
            this.RespuestaCuisMasivo = RespuestaCuisMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufd", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufd
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudCufd SolicitudCufd;
        
        public cufd()
        {
        }
        
        public cufd(srCodigos.solicitudCufd SolicitudCufd)
        {
            this.SolicitudCufd = SolicitudCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaCufd RespuestaCufd;
        
        public cufdResponse()
        {
        }
        
        public cufdResponse(srCodigos.respuestaCufd RespuestaCufd)
        {
            this.RespuestaCufd = RespuestaCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocado", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocado
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado;
        
        public notificaCertificadoRevocado()
        {
        }
        
        public notificaCertificadoRevocado(srCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado)
        {
            this.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocadoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaNotificaRevocado RespuestaNotificaRevocado;
        
        public notificaCertificadoRevocadoResponse()
        {
        }
        
        public notificaCertificadoRevocadoResponse(srCodigos.respuestaNotificaRevocado RespuestaNotificaRevocado)
        {
            this.RespuestaNotificaRevocado = RespuestaNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuis", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudCuis SolicitudCuis;
        
        public cuis()
        {
        }
        
        public cuis(srCodigos.solicitudCuis SolicitudCuis)
        {
            this.SolicitudCuis = SolicitudCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaCuis RespuestaCuis;
        
        public cuisResponse()
        {
        }
        
        public cuisResponse(srCodigos.respuestaCuis RespuestaCuis)
        {
            this.RespuestaCuis = RespuestaCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.solicitudCufdMasivo SolicitudCufdMasivo;
        
        public cufdMasivo()
        {
        }
        
        public cufdMasivo(srCodigos.solicitudCufdMasivo SolicitudCufdMasivo)
        {
            this.SolicitudCufdMasivo = SolicitudCufdMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srCodigos.respuestaCufdMasivo RespuestaCufdMasivo;
        
        public cufdMasivoResponse()
        {
        }
        
        public cufdMasivoResponse(srCodigos.respuestaCufdMasivo RespuestaCufdMasivo)
        {
            this.RespuestaCufdMasivo = RespuestaCufdMasivo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ServicioFacturacionCodigosChannel : srCodigos.ServicioFacturacionCodigos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioFacturacionCodigosClient : System.ServiceModel.ClientBase<srCodigos.ServicioFacturacionCodigos>, srCodigos.ServicioFacturacionCodigos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionCodigosClient() : 
                base(ServicioFacturacionCodigosClient.GetDefaultBinding(), ServicioFacturacionCodigosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionCodigosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionCodigosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.verificarComunicacionResponse srCodigos.ServicioFacturacionCodigos.verificarComunicacion(srCodigos.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacion(request);
        }
        
        public srCodigos.respuestaComunicacion verificarComunicacion()
        {
            srCodigos.verificarComunicacion inValue = new srCodigos.verificarComunicacion();
            srCodigos.verificarComunicacionResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).verificarComunicacion(inValue);
            return retVal.RespuestaComunicacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.verificarComunicacionResponse> srCodigos.ServicioFacturacionCodigos.verificarComunicacionAsync(srCodigos.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.verificarComunicacionResponse> verificarComunicacionAsync()
        {
            srCodigos.verificarComunicacion inValue = new srCodigos.verificarComunicacion();
            return ((srCodigos.ServicioFacturacionCodigos)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.verificarNitResponse srCodigos.ServicioFacturacionCodigos.verificarNit(srCodigos.verificarNit request)
        {
            return base.Channel.verificarNit(request);
        }
        
        public srCodigos.respuestaVerificarNit verificarNit(srCodigos.solicitudVerificarNit SolicitudVerificarNit)
        {
            srCodigos.verificarNit inValue = new srCodigos.verificarNit();
            inValue.SolicitudVerificarNit = SolicitudVerificarNit;
            srCodigos.verificarNitResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).verificarNit(inValue);
            return retVal.RespuestaVerificarNit;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.verificarNitResponse> srCodigos.ServicioFacturacionCodigos.verificarNitAsync(srCodigos.verificarNit request)
        {
            return base.Channel.verificarNitAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.verificarNitResponse> verificarNitAsync(srCodigos.solicitudVerificarNit SolicitudVerificarNit)
        {
            srCodigos.verificarNit inValue = new srCodigos.verificarNit();
            inValue.SolicitudVerificarNit = SolicitudVerificarNit;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).verificarNitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.cuisMasivoResponse srCodigos.ServicioFacturacionCodigos.cuisMasivo(srCodigos.cuisMasivo request)
        {
            return base.Channel.cuisMasivo(request);
        }
        
        public srCodigos.respuestaCuisMasivo cuisMasivo(srCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas)
        {
            srCodigos.cuisMasivo inValue = new srCodigos.cuisMasivo();
            inValue.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
            srCodigos.cuisMasivoResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).cuisMasivo(inValue);
            return retVal.RespuestaCuisMasivo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.cuisMasivoResponse> srCodigos.ServicioFacturacionCodigos.cuisMasivoAsync(srCodigos.cuisMasivo request)
        {
            return base.Channel.cuisMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.cuisMasivoResponse> cuisMasivoAsync(srCodigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas)
        {
            srCodigos.cuisMasivo inValue = new srCodigos.cuisMasivo();
            inValue.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).cuisMasivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.cufdResponse srCodigos.ServicioFacturacionCodigos.cufd(srCodigos.cufd request)
        {
            return base.Channel.cufd(request);
        }
        
        public srCodigos.respuestaCufd cufd(srCodigos.solicitudCufd SolicitudCufd)
        {
            srCodigos.cufd inValue = new srCodigos.cufd();
            inValue.SolicitudCufd = SolicitudCufd;
            srCodigos.cufdResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).cufd(inValue);
            return retVal.RespuestaCufd;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.cufdResponse> srCodigos.ServicioFacturacionCodigos.cufdAsync(srCodigos.cufd request)
        {
            return base.Channel.cufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.cufdResponse> cufdAsync(srCodigos.solicitudCufd SolicitudCufd)
        {
            srCodigos.cufd inValue = new srCodigos.cufd();
            inValue.SolicitudCufd = SolicitudCufd;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).cufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.notificaCertificadoRevocadoResponse srCodigos.ServicioFacturacionCodigos.notificaCertificadoRevocado(srCodigos.notificaCertificadoRevocado request)
        {
            return base.Channel.notificaCertificadoRevocado(request);
        }
        
        public srCodigos.respuestaNotificaRevocado notificaCertificadoRevocado(srCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado)
        {
            srCodigos.notificaCertificadoRevocado inValue = new srCodigos.notificaCertificadoRevocado();
            inValue.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
            srCodigos.notificaCertificadoRevocadoResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).notificaCertificadoRevocado(inValue);
            return retVal.RespuestaNotificaRevocado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.notificaCertificadoRevocadoResponse> srCodigos.ServicioFacturacionCodigos.notificaCertificadoRevocadoAsync(srCodigos.notificaCertificadoRevocado request)
        {
            return base.Channel.notificaCertificadoRevocadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(srCodigos.solicitudNotifcaRevocado SolicitudNotificaRevocado)
        {
            srCodigos.notificaCertificadoRevocado inValue = new srCodigos.notificaCertificadoRevocado();
            inValue.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).notificaCertificadoRevocadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.cuisResponse srCodigos.ServicioFacturacionCodigos.cuis(srCodigos.cuis request)
        {
            return base.Channel.cuis(request);
        }
        
        public srCodigos.respuestaCuis cuis(srCodigos.solicitudCuis SolicitudCuis)
        {
            srCodigos.cuis inValue = new srCodigos.cuis();
            inValue.SolicitudCuis = SolicitudCuis;
            srCodigos.cuisResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).cuis(inValue);
            return retVal.RespuestaCuis;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.cuisResponse> srCodigos.ServicioFacturacionCodigos.cuisAsync(srCodigos.cuis request)
        {
            return base.Channel.cuisAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.cuisResponse> cuisAsync(srCodigos.solicitudCuis SolicitudCuis)
        {
            srCodigos.cuis inValue = new srCodigos.cuis();
            inValue.SolicitudCuis = SolicitudCuis;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).cuisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srCodigos.cufdMasivoResponse srCodigos.ServicioFacturacionCodigos.cufdMasivo(srCodigos.cufdMasivo request)
        {
            return base.Channel.cufdMasivo(request);
        }
        
        public srCodigos.respuestaCufdMasivo cufdMasivo(srCodigos.solicitudCufdMasivo SolicitudCufdMasivo)
        {
            srCodigos.cufdMasivo inValue = new srCodigos.cufdMasivo();
            inValue.SolicitudCufdMasivo = SolicitudCufdMasivo;
            srCodigos.cufdMasivoResponse retVal = ((srCodigos.ServicioFacturacionCodigos)(this)).cufdMasivo(inValue);
            return retVal.RespuestaCufdMasivo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srCodigos.cufdMasivoResponse> srCodigos.ServicioFacturacionCodigos.cufdMasivoAsync(srCodigos.cufdMasivo request)
        {
            return base.Channel.cufdMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<srCodigos.cufdMasivoResponse> cufdMasivoAsync(srCodigos.solicitudCufdMasivo SolicitudCufdMasivo)
        {
            srCodigos.cufdMasivo inValue = new srCodigos.cufdMasivo();
            inValue.SolicitudCufdMasivo = SolicitudCufdMasivo;
            return ((srCodigos.ServicioFacturacionCodigos)(this)).cufdMasivoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionCodigosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionCodigosPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionCodigosClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionCodigosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionCodigosClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionCodigosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionCodigosPort,
        }
    }
}
